from pathlib import Path
from types import TracebackType
from typing import Required, Self, TypedDict

class TextTrace(TypedDict):
    type: int

class ExtractedImage(TypedDict, total=False):
    image: Required[bytes]
    ext: str
    width: int
    height: int

class Pixmap:
    def tobytes(self, output: str) -> bytes: ...

class Rect:
    def __init__(self, x0: float, y0: float, x1: float, y1: float) -> None: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...

class Page:
    @property
    def rect(self) -> Rect: ...
    def get_text(self, option: str) -> str: ...
    def get_texttrace(self) -> list[TextTrace]: ...
    def get_images(self, *, full: bool) -> list[tuple[int, ...]]: ...
    def get_image_rects(self, name: int) -> list[Rect]: ...
    def get_pixmap(self, *, dpi: int) -> Pixmap: ...
    def insert_image(self, rect: Rect, *, stream: bytes) -> int: ...
    def insert_text(
        self,
        point: tuple[float, float],
        text: str,
        *,
        render_mode: int = 0,
    ) -> int: ...

class Document:
    metadata: dict[str, str | None] | None
    @property
    def page_count(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def new_page(self) -> Page: ...
    def load_page(self, page_id: int) -> Page: ...
    def extract_image(self, xref: int) -> ExtractedImage: ...
    def set_metadata(self, metadata: dict[str, str]) -> None: ...
    def save(self, filename: str | Path) -> None: ...
    def close(self) -> None: ...

def open(filename: str | Path | None = None) -> Document: ...  # noqa: A001
